### PR TITLE
Fix #102 + Fix bug view if no reviews

### LINKED ISSUE #102: Fix color on chart if no vote for the note
Example on twisted timbers, if there's 0 vote, it keeps the last color.
Imo the problem comes from the sql query. Right now, it will not create a line for a note if there is no vote for this one.
For the chart, we still need the value even if it's 0.

### PR DESCRIPTION
**Pull request by shARPII**
@florian987 
#102 
I did not find a better solution than handling it inside the php class.
I could have useUNION inside the SQL query to get missing values stored in the table but it is not possible to use it with the manager.

Since we do not have default values set in a specific table, I thought handling the missing values in the query would be too ugly.

I don't know what you think about it, I am taking your recommandations on this one.

I also fixed a bug if there is no vote on the coaster and an other one if there is no reviews.

### CODE REVIEW

**Review by richardcrete — COMMENTED** [review]
It seems ok for me!

**Comment by florian987** [comment]
@shARPII I'd rather fix this at the chart level, because for me it's the only way we can ensure each color will be mapped to the correct rating value

So here is my suggestion:

```
colors:[
    function({seriesIndex, w}) {
        switch(w.globals.seriesNames[seriesIndex]) {
            case 5: return '#40bf40';
            case 4.5: return '#6ab31f';
            case 4: return '#84a600';
            case 3.5: return '#999800';
            case 3: return '#a98a00';
            case 2.5: return '#b57b00';
            case 2: return '#bd6b09';
            case 1.5: return '#c25c20';
            case 1: return '#c24d31';
            case 0.5: return '#bf4040';
        }
    }
],
```

**Comment by shARPII** [comment]
@florian987 thx, I agree, I changed it to your solution. You can check the PR and merge it if everything is ok.

**Review by florian987 — APPROVED** [review]
thanks!

**Pull request merged**
